services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - api
    volumes:
      - ./frontend:/frontend

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: